packages:
  - website
  - packages/*
  - editors/*

catalog:
  esbuild: ^0.27.4
  typescript: ^5.7.3
  vitest: ^3.1.1

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@vscode/vsce-sign'
  - esbuild
  - keytar
  - sharp
