import {
  chmodSync,
  mkdtempSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { spawnSync } from "node:child_process";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { describe, expect, it, afterEach } from "vitest";
import { verifies } from "@supersigil/vitest";
import { commandDetect, commandPrepare } from "./index.mjs";

const tempDirs = [];

afterEach(() => {
  while (tempDirs.length > 0) {
    rmSync(tempDirs.pop(), { recursive: true, force: true });
  }
});

function createTempRepo() {
  const dir = mkdtempSync(join(tmpdir(), "release-targets-test-"));
  tempDirs.push(dir);
  return dir;
}

function listReleaseTargetTempDirs() {
  return new Set(
    readdirSync(tmpdir(), { withFileTypes: true })
      .filter((entry) => entry.isDirectory() && entry.name.startsWith("release-targets-"))
      .map((entry) => entry.name),
  );
}

function writeTestFile(repoDir, relativePath, contents) {
  const path = join(repoDir, relativePath);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, contents, "utf8");
}

function run(dir, program, args) {
  const output = spawnSync(program, args, {
    cwd: dir,
    encoding: "utf8",
  });

  expect(output.status).toBe(0);

  return output.stdout;
}

function git(dir, ...args) {
  return run(dir, "git", args);
}

function gitCommit(dir, message = "fixture") {
  git(dir, "add", ".");
  git(dir, "commit", "-m", message);
}

function initFixtureRepo() {
  const dir = createTempRepo();

  git(dir, "init");
  git(dir, "config", "user.name", "Supersigil Tests");
  git(dir, "config", "user.email", "tests@supersigil.invalid");

  writeTestFile(
    dir,
    "release-targets.json",
    `{
  "targets": [
    {
      "id": "intellij",
      "enabled": false,
      "versionFile": "editors/intellij/gradle.properties",
      "versionKind": "gradle-property",
      "versionKey": "pluginVersion",
      "changelogFile": "editors/intellij/CHANGELOG.md",
      "cliffConfig": "cliff.intellij.toml",
      "impactPaths": [
        "editors/intellij/gradle.properties",
        "editors/intellij/src/main/**",
        "packages/preview/src/**",
        "packages/preview/styles/**",
        "packages/preview/scripts/**",
        "packages/preview/esbuild.mjs",
        "packages/preview/package.json"
      ],
      "excludePaths": [
        "editors/intellij/src/test/**",
        "packages/preview/**/__tests__/**",
        "packages/preview/**/*.test.ts",
        "packages/preview/**/*.snap"
      ]
    },
    {
      "id": "vscode",
      "enabled": true,
      "versionFile": "editors/vscode/package.json",
      "versionKind": "package-json",
      "versionKey": "version",
      "impactPaths": [
        "editors/vscode/src/**",
        "editors/vscode/package.json"
      ],
      "excludePaths": [
        "editors/vscode/src/**/*.test.ts"
      ]
    }
  ]
}
`,
  );
  writeTestFile(dir, "cliff.intellij.toml", "[changelog]\nbody = \"\"\n");
  writeTestFile(
    dir,
    "editors/intellij/gradle.properties",
    "pluginVersion = 0.1.0\n",
  );
  writeTestFile(dir, "editors/intellij/CHANGELOG.md", "# Changelog\n");
  writeTestFile(
    dir,
    "editors/vscode/package.json",
    '{\n  "version": "0.1.0"\n}\n',
  );
  writeTestFile(dir, "packages/preview/src/render.ts", "export const render = 1;\n");
  writeTestFile(
    dir,
    "packages/preview/__tests__/render.test.ts",
    "export const renderTest = 1;\n",
  );

  gitCommit(dir, "initial fixture");
  git(dir, "tag", "v0.1.0");

  return dir;
}

function runReleaseTargets(dir, args) {
  const previousDir = process.cwd();
  process.chdir(dir);

  try {
    const [subcommand, ...rest] = args;
    const options = {};

    for (let index = 0; index < rest.length; index += 1) {
      const arg = rest[index];
      if (!arg.startsWith("--")) {
        continue;
      }

      const key = arg.slice(2);
      const value = rest[index + 1];
      if (value === undefined || value.startsWith("--")) {
        options[key] = true;
        continue;
      }

      options[key] = value;
      index += 1;
    }

    if (subcommand === "detect") {
      return commandDetect(options);
    }
    if (subcommand === "prepare") {
      return commandPrepare(options);
    }

    throw new Error(`unsupported subcommand: ${subcommand}`);
  } finally {
    process.chdir(previousDir);
  }
}

function writeStubGitCliff(dir, { writeOutput = true } = {}) {
  const path = join(dir, "git-cliff-stub.mjs");
  const writeOutputSource = writeOutput
    ? `writeFileSync(
  output,
  "# Changelog\\n\\n## [" +
    tag.replace(/^v/, "") +
    "]\\n\\n### Features\\n\\n- Generated by stub git-cliff\\n",
);
`
    : "";
  writeFileSync(
    path,
    `#!/usr/bin/env node
import { writeFileSync } from "node:fs";

const args = process.argv.slice(2);

if (args[0] === "--version") {
  console.log("git-cliff-stub 0.0.0");
  process.exit(0);
}

let output = "";
let tag = "";

for (let index = 0; index < args.length; index += 1) {
  if (args[index] === "--output") {
    output = args[index + 1] ?? "";
    index += 1;
    continue;
  }

  if (args[index] === "--tag") {
    tag = args[index + 1] ?? "";
    index += 1;
  }
}

${writeOutputSource}
`,
    "utf8",
  );
  chmodSync(path, 0o755);
  return path;
}

function readCheckedInReleaseTargets() {
  return JSON.parse(
    readFileSync(new URL("../../release-targets.json", import.meta.url), "utf8"),
  );
}

function getCheckedInTarget(targetId) {
  const config = readCheckedInReleaseTargets();
  const target = config.targets.find(({ id }) => id === targetId);
  expect(target).toBeDefined();
  return target;
}

describe("release-targets helper", () => {
  it(
    "keeps the release workflow pointed at the checked-in helper entrypoint",
    verifies("release-targets/req#req-4-1"),
    () => {
      const workflow = readFileSync(
        new URL("../../.github/workflows/release.yml", import.meta.url),
        "utf8",
      );

      expect(workflow).toContain(
        'node scripts/release-targets/index.mjs detect --head-ref "${GITHUB_REF_NAME}" --github-output "${GITHUB_OUTPUT}"',
      );
    },
  );

  it(
    "tracks shared pnpm manifests for targets built from pnpm-managed JS sources",
    verifies("release-targets/req#req-1-4"),
    () => {
      for (const targetId of [
        "intellij",
        "vscode",
        "npm-vitest",
        "npm-eslint-plugin",
      ]) {
        const target = getCheckedInTarget(targetId);
        expect(target.impactPaths).toContain("pnpm-workspace.yaml");
        expect(target.impactPaths).toContain("pnpm-lock.yaml");
      }
    },
  );

  it(
    "tracks VS Code packaged README and license files as shipped inputs",
    verifies("release-targets/req#req-1-4"),
    () => {
      const target = getCheckedInTarget("vscode");

      expect(target.impactPaths).toContain("editors/vscode/README.md");
      expect(target.impactPaths).toContain("editors/vscode/LICENSE");
    },
  );

  it(
    "tracks VS Code shared preview and webview sources as shipped inputs",
    verifies("release-targets/req#req-1-3", "release-targets/req#req-1-4"),
    () => {
      const target = getCheckedInTarget("vscode");

      for (const path of [
        "packages/preview/src/**",
        "packages/preview/styles/**",
        "packages/preview/scripts/**",
        "packages/preview/esbuild.mjs",
        "packages/preview/package.json",
        "website/src/components/explore/**",
        "website/src/styles/landing-tokens.css",
      ]) {
        expect(target.impactPaths).toContain(path);
      }
    },
  );

  it(
    "detects impacted shipped-input changes for disabled targets",
    verifies(
      "release-targets/req#req-1-4",
      "release-targets/req#req-2-1",
      "release-targets/req#req-4-3",
    ),
    () => {
      const dir = initFixtureRepo();

      writeTestFile(dir, "packages/preview/src/render.ts", "export const render = 2;\n");
      gitCommit(dir, "shipped change");

      const output = runReleaseTargets(dir, ["detect", "--base-ref", "v0.1.0", "--json"]);

      expect(output.targets.intellij.impacted).toBe(true);
      expect(output.targets.intellij.publish).toBe(false);
    },
  );

  it(
    "ignores excluded test-only changes",
    verifies("release-targets/req#req-2-4"),
    () => {
      const dir = initFixtureRepo();

      writeTestFile(
        dir,
        "packages/preview/__tests__/render.test.ts",
        "export const renderTest = 2;\n",
      );
      gitCommit(dir, "test-only change");

      const output = runReleaseTargets(dir, ["detect", "--base-ref", "v0.1.0", "--json"]);

      expect(output.targets.intellij.impacted).toBe(false);
    },
  );

  it(
    "ignores version-only changes in version files",
    verifies("release-targets/req#req-1-4"),
    () => {
      const dir = initFixtureRepo();

      writeTestFile(
        dir,
        "editors/intellij/gradle.properties",
        "pluginVersion = 0.1.1\n",
      );
      writeTestFile(
        dir,
        "editors/vscode/package.json",
        '{\n  "version": "0.1.1"\n}\n',
      );
      gitCommit(dir, "version-only change");

      const output = runReleaseTargets(dir, ["detect", "--base-ref", "v0.1.0", "--json"]);

      expect(output.targets.intellij.impacted).toBe(false);
      expect(output.targets.vscode.impacted).toBe(false);
    },
  );

  it(
    "prepares only impacted target versions and changelogs",
    verifies(
      "release-targets/req#req-3-2",
      "release-targets/req#req-3-3",
      "release-targets/req#req-5-1",
    ),
    () => {
      const dir = initFixtureRepo();
      const gitCliff = writeStubGitCliff(dir);

      writeTestFile(dir, "packages/preview/src/render.ts", "export const render = 2;\n");
      gitCommit(dir, "shipped change");

      const output = runReleaseTargets(dir, [
        "prepare",
        "--base-ref",
        "v0.1.0",
        "--version",
        "0.2.0",
        "--git-cliff-bin",
        gitCliff,
        "--json",
      ]);

      expect(output.targets.intellij.impacted).toBe(true);
      expect(readFileSync(join(dir, "editors/intellij/gradle.properties"), "utf8")).toContain(
        "pluginVersion = 0.2.0",
      );
      expect(readFileSync(join(dir, "editors/vscode/package.json"), "utf8")).toContain(
        '"version": "0.1.0"',
      );
      expect(readFileSync(join(dir, "editors/intellij/CHANGELOG.md"), "utf8")).toContain(
        "Generated by stub git-cliff",
      );
    },
  );

  it(
    "leaves target files unchanged when the target is not impacted",
    verifies(
      "release-targets/req#req-3-4",
      "release-targets/req#req-5-3",
    ),
    () => {
      const dir = initFixtureRepo();

      const versionBefore = readFileSync(join(dir, "editors/intellij/gradle.properties"), "utf8");
      const changelogBefore = readFileSync(join(dir, "editors/intellij/CHANGELOG.md"), "utf8");

      const output = runReleaseTargets(dir, [
        "prepare",
        "--base-ref",
        "v0.1.0",
        "--version",
        "0.2.0",
        "--json",
      ]);

      expect(output.targets.intellij.impacted).toBe(false);
      expect(readFileSync(join(dir, "editors/intellij/gradle.properties"), "utf8")).toBe(
        versionBefore,
      );
      expect(readFileSync(join(dir, "editors/intellij/CHANGELOG.md"), "utf8")).toBe(
        changelogBefore,
      );
    },
  );

  it(
    "does not rewrite target files when git-cliff validation fails",
    verifies("release-targets/req#req-2-5"),
    () => {
      const dir = initFixtureRepo();

      writeTestFile(dir, "packages/preview/src/render.ts", "export const render = 2;\n");
      gitCommit(dir, "shipped change");

      const versionBefore = readFileSync(join(dir, "editors/intellij/gradle.properties"), "utf8");
      const changelogBefore = readFileSync(join(dir, "editors/intellij/CHANGELOG.md"), "utf8");

      expect(() =>
        runReleaseTargets(dir, [
          "prepare",
          "--base-ref",
          "v0.1.0",
          "--version",
          "0.2.0",
          "--git-cliff-bin",
          "/definitely/missing/git-cliff",
        ]),
      ).toThrow(/failed/);
      expect(readFileSync(join(dir, "editors/intellij/gradle.properties"), "utf8")).toBe(
        versionBefore,
      );
      expect(readFileSync(join(dir, "editors/intellij/CHANGELOG.md"), "utf8")).toBe(
        changelogBefore,
      );
    },
  );

  it(
    "cleans up temporary changelog directories when the renderer omits output",
    verifies("release-targets/req#req-2-5"),
    () => {
      const dir = initFixtureRepo();
      const gitCliff = writeStubGitCliff(dir, { writeOutput: false });
      const beforeTempDirs = listReleaseTargetTempDirs();

      writeTestFile(dir, "packages/preview/src/render.ts", "export const render = 2;\n");
      gitCommit(dir, "shipped change");

      expect(() =>
        runReleaseTargets(dir, [
          "prepare",
          "--base-ref",
          "v0.1.0",
          "--version",
          "0.2.0",
          "--git-cliff-bin",
          gitCliff,
        ]),
      ).toThrow(/failed to read rendered changelog/);

      const afterTempDirs = listReleaseTargetTempDirs();
      expect([...afterTempDirs].filter((name) => !beforeTempDirs.has(name))).toEqual([]);
    },
  );

  it(
    "writes GitHub outputs with publish flags",
    verifies(
      "release-targets/req#req-2-2",
      "release-targets/req#req-4-1",
    ),
    () => {
      const dir = initFixtureRepo();
      const githubOutput = join(dir, "github-output.txt");

      writeTestFile(dir, "editors/vscode/src/extension.ts", "export const vscode = 1;\n");
      gitCommit(dir, "vscode change");

      runReleaseTargets(dir, [
        "detect",
        "--base-ref",
        "v0.1.0",
        "--github-output",
        githubOutput,
      ]);

      const outputs = readFileSync(githubOutput, "utf8");
      expect(outputs).toContain("impacted_vscode=true");
      expect(outputs).toContain("publish_vscode=true");
      expect(outputs).toContain("publish_intellij=false");
    },
  );
});
