name: Publish npm

on:
  workflow_call:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  npm:
    name: Publish to npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0

      - name: Setup Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: "22"
          cache: pnpm
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Publish @supersigil/vitest
        run: pnpm publish --no-git-checks --access public --provenance
        working-directory: packages/vitest

      - name: Publish @supersigil/eslint-plugin
        run: pnpm publish --no-git-checks --access public --provenance
        working-directory: packages/eslint-plugin
